"""empty message

Revision ID: 1abe47f3d9c5
Revises: 9bae26b5408b
Create Date: 2020-08-30 17:29:05.912060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abe47f3d9c5'
down_revision = '9bae26b5408b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('break_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_column('break_start')
        batch_op.drop_column('break_end')

    # ### end Alembic commands ###
