"""empty message

Revision ID: 1ffa9df238d9
Revises: 1abe47f3d9c5
Create Date: 2020-08-30 17:43:27.313637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffa9df238d9'
down_revision = '1abe47f3d9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('break_start', sa.DateTime(), nullable=True),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendars_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendars'))
    )
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_name', sa.String(length=64), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_weeks_calendar_id_calendars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weeks'))
    )
    op.create_table('todoitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_todoitems_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todoitems'))
    )
    op.drop_table('week')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    op.drop_table('to_do_item')
    op.drop_table('calendar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('break_end', sa.DATETIME(), nullable=True),
    sa.Column('break_start', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_do_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=128), nullable=True),
    sa.Column('week_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('has_calendar', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('has_calendar IN (0, 1)'),
    sa.CheckConstraint('has_calendar IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    op.create_table('week',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('week_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], name='fk_week_calendar_id_calendar'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todoitems')
    op.drop_table('weeks')
    op.drop_table('calendars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
